name: Clans
main: com.echo28.bukkit.clans.Clans
version: 1.2.1
commands:
  clan:
    description: Work with clans
    usage: Invalid usage, type /<command> help for help
  cc:
    description: Clan chat
    usage: Invalid usage, type /<command> <message> - Talk to your clan members
  ccc:
    description: Clan Council chat
    usage: Invalid usage, type /<command> <message> - Talk to your clan council
  ch:
    description: Clan hall
    usage: Invalid usage, type /<command> - Warp to your clan hall